auth_enabled: false

server:
  http_listen_port: 3100
  http_grpc_listen_port: 9096

ingester:
  chunk_target_size: 1048576
  max_chunk_age: 1h
  max_retention: 0s

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

schema_config:
  configs:
    - from: 2020-01-01
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 168h

limits_config:
  max_query_length: 0
  max_query_parallelism: 32